name: model_collaboration3
channels:
  - defaults
  - nodefaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - gh=2.74.2=h76a2195_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.4.0
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - attrs==25.3.0
      - bayesian-optimization==1.4.0
      - blis==1.3.3
      - boto3==1.39.3
      - botocore==1.39.3
      - catalogue==2.0.10
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.2
      - cma==4.4.2
      - codetiming==1.4.0
      - confection==0.1.5
      - cymem==2.0.13
      - datasets==4.0.0
      - deap==1.4.3
      - dill==0.3.8
      - directsearch==1.0.1
      - distro==1.9.0
      - einops==0.8.2
      - emoji==2.15.0
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.1
      - hydra-core==1.3.2
      - idna==3.10
      - immutabledict==4.2.2
      - immutables==0.21
      - importlib-metadata==8.7.1
      - inquirerpy==0.3.4
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - langdetect==1.0.9
      - line-profiler==5.0.0
      - markupsafe==3.0.2
      - mergekit==0.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.6.3
      - multiprocess==0.70.16
      - murmurhash==1.0.15
      - networkx==3.5
      - nevergrad==1.0.12
      - nltk==3.9.2
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==1.93.2
      - orjson==3.11.6
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.16.0
      - pfzy==0.3.4
      - pillow==11.2.1
      - platformdirs==4.5.1
      - preshed==3.0.12
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvers==0.2.2
      - pyyaml==6.0.2
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2024.11.6
      - requests==2.32.4
      - rpds-py==0.30.0
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-learn==1.7.2
      - scipy==1.16.1
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.51.0
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - syllapy==0.7.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensordict==0.11.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - torch-geometric==2.7.0
      - torchaudio==2.7.1
      - torchdata==0.11.0
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.53.0
      - triton==3.3.1
      - trl==0.19.1
      - typer-slim==0.21.1
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.24.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.3
      - wrapt==2.0.1
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /opt/conda/envs/model_collaboration3
